# Generated by Django 3.0.4 on 2020-03-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Url', '0002_auto_20200308_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
